""" Zombie NPC Player """
from __future__ import annotations
# from GameState import GameState
import GameState
from PlayerState import PlayerState
from Utils import json_cmd_simple


class NPCZombieState(PlayerState):
    def _init_(self):
        self.notes = "Du bist verwirrt."
        self.gameengine_returns = ""

    def NPC_game_move(self, gs:GameState.GameState) -> {}:
        """ Zombie Player inputs its actions to the game engine with this method

        The main game loop will call this function in order to get a single command it
        shall execute for the zombie player.

        The game loop the executes the command and returns its results to NPC_process_gs_result,
        which then generates a new notes entry
        """
        return json_cmd_simple("nichts")

    def NPC_process_gs_result(self, gs:GameState.GameState, results) -> {}:
        """ Handle the results of the game engine:
        Have the LLM Create a new self.notes based on
        - the last prompt,
        - the last command generated from the prompt by the llm and
        - the results generated by the game engine
        """
        self.notes = "Neue Notizen hierhin!"

    def compile_zombie_context(self, gs:GameState.GameState) -> {}:
        """ Zombie Player context:
            This function gathers the context from GameEngine in order to prepare the prompt for the zombie player.

            Items of interest:
            - Where is the zombie player?
            - What objects are here?
            - Where can he go from here?
            - Who ist in the same location? Provide all "visible" data
            - For all visible and non-obstructed neighbor places:
              - Who is in that place?
        """
        return {}

    def compile_zombie_prompt(self, gs:GameState.GameState) -> str:
        """ Zombie Player prompt:
        This function gathers the prompt for the zombie player.

        The prompt will be conveyed to the llm in order to produce a command for the game engine - the next
        step for the zombie player.

        The prompt shall contain:
        - The overall "system" prompt for the zombie ("Du bist ein NPC in einem Adventure-Spiel...")
        - The overall goal of the zombie player.
        - The current context of the zombie player (compile_zombie_context() above)
        - The strategy notes the zombie player generated in the last move
        - The list of commands (tool calls) the zombie player can generate

        In subsequent steps, this prompt will be sent to the LLM in order to generate one single command in
        NPC_game_move. The game loop above will then execute the command and feed back the results to the
        NPCZombieState object via NPC_process_gs_results()
        """
        prompt = ""
        zcontext = self.compile_zombie_context(gs)

        return prompt

    def game_engine_answer(self, gs:GameState.GameState, r:str):
        """
        Zombie issues commands to game engine like any other player. The game engines
        answers are stored in the Zombie object so it can be processed in subsequent calls
        to NPC_game_move.
        """
        self.gameengine_returns = r