#from Adventure6 import places, state, items, gehe, nimm, untersuche, anwenden, umsehen, inventory
# from Door import Door
# from InteractLLM import PromptGenerator
#

from collections import deque

import Utils


class SysTest:
    def __init__(self):

        #
        # For testing purposes rename any of the following to "test_queue"
        #
        self.test_queue_1 = deque([
            "gehe schuppen",
            "untersuche blumentopf",
            "anwenden schlüssel schuppen",
            "gehe innen",
            "nimm sprengladung",
            "gehe schuppen",
            "gehe felsen",
            #"umsehen",
            "anwenden sprengladung",
            "ablegen sprengladung",
            "gehe schuppen",
            "gehe innen",
            "untersuche skelett",
            "untersuche geldboerse",
            "nimm ec-karte",
            "nimm leiter",
            "gehe schuppen",
            "anwenden leiter schuppen",
            "gehe felsen",
            "gehe höhle",
            "anwenden hauptschalter",
            "gehe felsen",
            "gehe schuppen",
            "gehe dach",
            "anwenden hebel",
            "gehe schuppen",
            "gehe warenautomat",
            "gehe ubahn",
            "untersuche muelleimer",
            "nimm geheimzahl",
            "gehe warenautomat",
            "nichts",
            "nichts",
            "gehe ubahn",
            "anwenden wasserspender",
            "nichts",
            "gehe wagen",
            "nichts",
            "nichts",
            "gehe ubahn",
            "gehe warenautomat",
            "gehe geldautomat",
            "inventory",
            "anwenden ec-karte geldautomat",
            "nimm us-dollar",
            "gehe warenautomat",
            "gehe ubahn",
            "nichts",
            "nichts",
            "gehe warenautomat",
            "nichts",
            "nichts",
            "gehe ubahn",
            "gehe wagen",
            "anwenden türschließer"
        ])

        self.test_queue_cheese = deque([
            "gehe schuppen",
            "untersuche blumentopf",
            "anwenden schlüssel schuppen",
            "gehe innen",
            "nimm sprengladung",
            "gehe schuppen",
            "gehe warenautomat",
            "anwenden sprengladung warenautomat",
            #"ablegen sprengladung",
            "gehe schuppen",
            "nichts"
        ])
        self.test_queue_long = deque([
            # "gehe geldautomat",
            #
            # Hundekampf provozieren
            #
            # "nichts",
            # "nichts",
            # "nichts",
            # "nichts",
            # "nichts",
            # "nichts",
            # "nichts",
            "gehe p_schuppen",
            "umsehen",
            "untersuche Blumentopf",
            "anwenden Schlüssel Schuppen",
            "gehe p_innen",
            "umsehen",
            "nimm sprengladung",
            "gehe p_schuppen",
            "gehe felsen",
            "umsehen",
            "anwenden sprengladung",
            "ablegen sprengladung",
            "gehe p_schuppen",
            "gehe p_innen",
            "nichts",
            "gehe p_schuppen",
            "gehe p_felsen",
            "umsehen",
            "gehe höhle",
            "umsehen",
            "anwenden breaker",
            "gehe felsen",
            "gehe p_schuppen",
            "gehe p_innen",
            "untersuche o_skelett",
            "untersuche o_geldboerse",
            "nimm o_ec_karte",
            "nimm o_leiter",
            "gehe p_schuppen",
            "anwenden o_leiter o_schuppen",
            "gehe p_dach",
            "umsehen",
            "anwenden o_hebel",
            "gehe p_schuppen",
            "anwenden o_ec_karte o_blumentopf",
            "gehe p_geldautomat",
            # "anwenden o_ec_karte o_geldautomat",
            "gehe p_warenautomat",
            "umsehen",
            "gehe p_ubahn",
            "umsehen",
            "untersuche o_muelleimer",
            "untersuche o_geheimzahl",
            "nimm o_geheimzahl",
            "gehe p_warenautomat",
            "gehe p_geldautomat",
            "untersuche o_geheimzahl",
            "anwenden o_ec_karte o_geldautomat",
            "gehe p_warenautomat",
            "gehe p_ubahn",
            "gehe p_wagen",
            "umsehen",
            "nimm o_salami",
            "gehe p_ubahn",
            "gehe p_warenautomat",
            "gehe p_schuppen",
            "ablegen o_salami",
            "umsehen",
            "gehe p_innen",
            "nichts",
            "nichts",
            "gehe p_schuppen",
            "gehe p_geldautomat",
            "nimm o_geld_dollar",
            "gehe p_warenautomat",
            "anwenden o_geld_dollar o_warenautomat",
            "gehe p_schuppen",
            "nichts",
            "nichts",
            "nichts",
            "gehe p_dach",
            "anwenden o_hebel",
            "gehe p_schuppen",
            "gehe p_warenautomat",
            "umsehen",
            "anwenden o_geld_dollar o_warenautomat",
            "untersuche o_warenautomat",
            "nichts",
            "gehe schuppen",
            "gehe dach",
            "anwenden hebel",
            "gehe schuppen",
            "gehe warenautomat",
            "gehe u-bahn",
            "gehe wagen",
            "umsehen",
            "anwenden turschliesser",
            "gehe p_ubahn2",
            "umsehen",
            "anwenden o_geld_dollar o_pizzaautomat",
            "umsehen",
            "nimm pizza",
            "nimm lire",
            "gehe wagen",
            "anwenden tuerschliesser",
            "gehe ubahn",
            "gehe warenautomat",
            "anwenden lire warenautomat",
            "gehe schuppen",
            "gehe dach",
            "anwenden hebel",
            "gehe schuppen",
            "gehe warenautomat",
            "nichts"

        ])
        self.test_queue_llm = deque([
            "gehe zum schuppen und schau dich um",
            "untersuche den blumentopf",
            "schließe mit dem schlüssel den Schuppen auf und gehe hinein",
         #   "gehe innen",
            "sieh dich um",
            "nimm die sprengladung und verlasse den schuppen",
         #   "gehe schuppen",
            "gehe zum felsen",
            "sieh dich um",
            "aktiviere die Sprengladung und lege sie am Felsen ab",
          #  "ablegen sprengladung",
            "gehe zum schuppen",
            "gehe nach innen",
            "untersuche das skelett",
            "untersuche die geldboerse",
            "nimm die ec-karte und die Leiter",
           # "nimm leiter",
            "verlasse den schuppen",
            "lehne die Leiter an den Schuppen",
          # "anwenden leiter schuppen",
            "gehe zum felsen",
            "gehe in die höhle",
            "umschauen",
            "betätige den hauptschalter und verlasse die höhle",
           # "gehe felsen",
            "gehe zum schuppen",
            "steige auf das dach",
           # "gehe dach",
            "umsehen",
            "betätige den Hebel",
            "springe vom schuppen und gehe zum warenautomat",
           # "gehe warenautomat",
            "gehe zum u-bahnhof",
            "untersuche den mülleimer",
            "nimm den Zettzel mit der geheimzahl",
            "gehe wieder an die Oberfläche",
            "nichts",
            "nichts",
            "gehe zur u-bahn",
            "trinke vom Wasserspender",
            "nichts",
            "gehe in den wagen",
            "nichts",
            "nichts",
            "verlasse den Wagen",
            "Gehe wieder an die Oberfläche",
            "gehe zum geldautomat",
            "inventory",
            "Stecke die Geldkarte in den Geldautomaten",
            "nimm die us-dollar",
            "gehe zum warenautomat",
            "gehe in die ubahn",
            "nichts",
            "nichts",
            "gehe wieder nach oben",
            "nichts",
            "nichts",
            "gehe zur ubahn",
            "gehe gehe in den wagen und betätige den türschließer",
            # "anwenden türschließer",
            "umsehen",
            "gehe auf den bahnsteig",
            "umsehen",
            "untersuche den pizzaautomaten",
            "wirf die US-Dollar in den Pizzaautomaten",
            "nimm die lire und die pizza",
            "gehe in den wagen und betätige den türschließer",
            "verlasse den wagen",
            "trinke vom wasserspender",
            "gehe an die oberfläche",
            "gehe zum schuppen und lege die pizza ab",
            "steige auf den schuppen",
            "betätige den hebel",
            "springe vom schuppen und gehe zum warenautomaten",
            "wirf die lire in den warenautomat",
            "nimm die fahrradkette und gehe zum start",
            "baue die fahrradkette in das fahrrad ein",

        ])

        from Utils import dl
        if Utils.DEBUG_LEVEL & dl.SYSTEST:
            self.test_queue = self.test_queue_1
        else:
            self.test_queue = deque([])

    def test_game(self) -> str:
        from Utils import dprint, dl
        if self.test_queue:
            c = self.test_queue.popleft()
            dprint (dl.PLAYERSTATE, 'Player: {c}')
            return c
        else:
            return None

    def test_game_llm(self) -> str:
        from Utils import dprint, dl
        if self.test_queue_llm:
            c = self.test_queue_llm.popleft()
            dprint (dl.PLAYERSTATE, 'Player: {c}')
            print(f"Spieler: {c}")
            return c
        else:
            return None


