from __future__ import annotations
from typing import Protocol, Any, Mapping, Sequence

class LLMClient(Protocol):
    def gen_narration_prompt(self, gs: Any, pl: Any) -> str: ...
    def clean_truncated_sentence(self, text: str) -> str: ...
    def narrate(self, gs: Any, pl: Any) -> str: ...
    def validate_llm_tools_schema(self, tools_list: Sequence[Mapping[str, Any]]) -> None: ...
    def parse_user_input_to_commands(self, user_input: str, game_context_for_tools: Mapping[str, Any]) -> list[Mapping[str, Any]]: ...
    def get_npc_action(self, game_state_for_npc: Mapping[str, Any]) -> Mapping[str, Any]: ...
